[package]
name = "tornado-opt-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "1.0.30", features = ["rand"] }
ark-ff = { version = "0.5.0" }
ark-bn254 = { version = "0.5.0" }
ark-crypto-primitives = { version = "0.5.0", features = ["crh"] }
